markdown: kramdown
baseurl: 'https://www.draytonestate.com/'
url: 'https://www.draytonestate.com/'
exclude: ['README.md']
permalink: /:title/
include: ["_pages"]
sass:
  sass_dir:          _sass
  style:            :compressed
plugins:
  - jekyll-sitemap
